name: 'Workflow'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  job:
    name: Job
    runs-on: ubuntu-latest

    steps:
      - name: Default PATH
        run: echo $PATH

      - name: Input
        run: echo $DOCKER_IMAGES
        env:
          DOCKER_IMAGES: name/image
